Swen testnet deploy
Lightprotocol/light-protocol pull request #234
Opened 2023-08-27 11:45 UTC by SwenSchaeferjohann

2023-08-27 12:39 UTC, SwenSchaeferjohann commented
tangentially related: 

- test: payments app use testnet + indexer
- cli with testnet (blocked)

2023-08-27 23:16 UTC, ananas-block requested changes

2023-08-27 23:16 UTC, ananas-block commented on relayer/package.json
> +    "@lightprotocol/zk.js": "0.3.2-alpha.13",
We need this to import by path for testing. What about doing relayer release branches which have the actual version number and will be deployed?

2023-08-27 23:16 UTC, ananas-block commented on relayer/src/config.ts
> +console.log("PASS: ", PASSWORD);
let's remove at least this log

2023-08-27 23:16 UTC, ananas-block commented on relayer/tests/browser_test.ts
> +    await connection.requestAirdrop(relayerRecipientSol, 2 * AIRDROP_DECIMALS);
happy for a SOL_DECIMALS constant in zk.js but I don't think it's good to start putting such constants in many different places.

2023-08-29 00:18 UTC, ananas-block commented on relayer/tests/browser_test.ts
> +      new BN(5000),
why did you reduce the relayer fee?
(We do 100k in all our tests)

2023-08-29 16:06 UTC, ananas-block approved these changes

2023-08-29 16:07 UTC, merged