chore: Unify the `MERKLE_TREE_HEIGHT` constant
Lightprotocol/light-protocol pull request #292
Opened 2023-10-02 11:39 UTC by vadorovsky

Use it both for Transaction and Event Merkle Tree.

2023-10-02 15:55 UTC, ananas-block approved these changes

2023-10-02 15:59 UTC, ananas-block requested changes
I was a bit quick on approving. All the changes you made look good!
What about the following places where we pass the height of the Merkle tree?
https://github.com/Lightprotocol/light-protocol/blob/vadorovsky/merkle-tree-height/system-programs/programs/merkle_tree_program/src/lib.rs#L77
https://github.com/Lightprotocol/light-protocol/blob/ae8a6cbcd3bd35635e9200ce9aef5355c3454fda/system-programs/programs/merkle_tree_program/src/lib.rs#L106

2023-10-03 09:19 UTC, vadorovsky commented
@ananas-block done

2023-10-03 23:03 UTC, ananas-block approved these changes

2023-10-03 23:04 UTC, merged