perf: add merkleProof circuit benchmarks
Lightprotocol/light-protocol pull request #298
Opened 2023-10-03 13:43 UTC by Shigoto-dev19

Changes:
- Add a new `benchmarks` dir inside `circuit-lib/ciruit-lib.circom`
- Use [micro-bmark](https://github.com/paulmillr/micro-bmark) package for micro benchmarks
- Benchmark `merkleProof` circuit directly comparing heights in [18, 20, 22, 24, 26]
- Add benchmarks README.md summary for the `merkleProof` circuit.
- The Merkle Tree is initialized with 2^16 elements generated from a Field Element PRNG(imported from `maci-crypto`)
- The leaf input for benchmarks is constant and taken as `elements[2]` (agnostic to performance) because using a random sample adds noise to benchmarks

2023-10-03 15:08 UTC, ananas-block reviewed
Looks good in general just a couple small things.

2023-10-03 15:10 UTC, ananas-block commented on circuit-lib/circuit-lib.circom/src/merkle-tree/merkleProof.circom
> +include "../../node_modules/circomlib/circuits/switcher.circom";
this might be the reason for the red tests as well

2023-10-03 17:01 UTC, Shigoto-dev19 commented on circuit-lib/circuit-lib.circom/benchmarks/merkle-tree/README.md
> +***iterations** = 2000*
it is italic bold in markdown

2023-10-03 17:01 UTC, Shigoto-dev19 commented on circuit-lib/circuit-lib.circom/benchmarks/merkle-tree/README.md
> +| Height | Capacity | Operations per Second | Average Execution Time |
done!

2023-10-03 17:19 UTC, Shigoto-dev19 commented on circuit-lib/circuit-lib.circom/src/merkle-tree/merkleProof.circom
> +include "../../node_modules/circomlib/circuits/switcher.circom";
fixed by adding the flag directly to circom_tester compiler

2023-10-09 14:50 UTC, ananas-block requested changes

2023-10-09 14:50 UTC, ananas-block commented on circuit-lib/circuit-lib.circom/benchmarks/merkle-tree/merkleProof-height.ts
> +      wasm_tester(`./tests/merkle-tree/merkleProof_test${height}.circom`, {
The bench results are quite different from the results in light_transaction benchmarks.

Can you switch this to snarkjs please for better comparability?
(If you make the bench generation function a generic utility it should be pretty quick to do.)

2024-02-19 04:13 UTC, closed without merging