refactor: Reorganize the project structure
Lightprotocol/light-protocol pull request #318
Opened 2023-10-07 01:43 UTC by vadorovsky

* Rename programs - these names are going to be used on crates.io:
  * `merkle_tree_program` -> `light-merkle-tree-program`
  * `verifier_program_zero` -> `light-psp-two-two`
  * `verifier_program_one` -> `light-psp-ten-two`
  * `verifier_program_two` -> `light-psp-four-four`
  * `verifier_program_storage` -> `light-psp-two-two-storage`
* Merge all Rust crates into one workspace.
* Rename `system-programs` to `programs` - unfortunately, when moving `Cargo.toml` and `Anchor.toml` to the top, Anchor was struggling with finding program crates anywhere outside `programs/*`.
* Stricter rustfmt rules.

2023-10-07 01:45 UTC, vadorovsky commented on psp-examples/swap/circuits/swaps/swaps.circom
> +/**
This file is unrelated to the goal of this PR, but I think it's a good change to make? Seems like this circuit was never commited, even though it's clearly produced by macro-circum whenever the swap PSP is built.

2023-10-10 17:34 UTC, ananas-block requested changes
This naming is also not consistent anymore but could also be adapted in a future pr:
https://github.com/Lightprotocol/light-protocol/blob/main/zk.js/src/utils.ts#L12

2023-10-11 06:05 UTC, vadorovsky commented on programs/package.json
Yes - this `programs` package needs to exist, so we can depend on it in other packages, like cli:

https://github.com/Lightprotocol/light-protocol/pull/318/files#diff-088b5e0ac52dd36816ebc6b121d5423c763c3c18c098b91757c014937c7d632dR47

This way we always make sure that programs are built before.

2023-10-11 07:18 UTC, vadorovsky commented on circuit-lib/circuit-lib.circom/scripts/checkBuildCircuit.sh
> +check_file_modified ../../programs/verifier_program_one/src/verifying_key.rs
Done,

2023-10-11 10:50 UTC, ananas-block commented on programs/package.json
Ah I see

2023-10-11 12:51 UTC, merged