feat: docker fix (works with latest repo structure)
Lightprotocol/light-protocol pull request #331
Opened 2023-10-13 02:13 UTC by SwenSchaeferjohann

- extracted from https://github.com/Lightprotocol/light-protocol/pull/327 into dedicated PR for clarity
- adds a working script for relayer deployment on digitalocean

2023-10-13 02:14 UTC, SwenSchaeferjohann commented
preferably merge directly after #327

2023-10-13 15:24 UTC, ananas-block requested changes
I think it makes sense to add a test, otherwise looks good, to me.

2023-10-13 15:24 UTC, ananas-block commented on scripts/deployRelayer.sh
> +docker tag relayer-app:latest registry.digitalocean.com/v3-relayer/relayer-app:latest
Two ideas how to test this script:

1. add a test flag which let's you skip line 94-96. This way you can build docker but not deploy it.
2. separate the script into two, the first builds docker, the second uses the first to build docker and deploys it. The test would only test the first script.

2023-10-14 19:39 UTC, ananas-block commented on scripts/buildDocker.sh
What about naming these files ```buildDockerRelayer.sh```, ```deployDockerRelayer.sh```, ```testDockerRelayer.sh```?

2023-10-15 16:05 UTC, ananas-block approved these changes

2023-10-15 16:05 UTC, merged