feat(cli): Fetch programs from corresponding tags
Lightprotocol/light-protocol pull request #347
Opened 2023-10-18 16:26 UTC by vadorovsky

2023-10-18 23:52 UTC, ananas-block requested changes

2023-10-18 23:52 UTC, ananas-block commented on cli/src/psp-utils/constants.ts
>  export const PROGRAM_TAG = "v0.3.2";
Are we still using this tag?

2023-10-18 23:52 UTC, ananas-block commented on cli/src/psp-utils/constants.ts
> +export const LIGHT_PSP2IN2OUT_STORAGE_TAG = "light";
```suggestion
export const LIGHT_PSP2IN2OUT_STORAGE_TAG = "light-psp2in2out-storage-v0.3.0";
```

2023-10-18 23:52 UTC, ananas-block commented on cli/src/utils/initTestEnv.ts
> +      tag: SPL_NOOP_PROGRAM_TAG,
It looks to me as if these tags are not used yet, but still PROGRAM_TAG.
see: https://github.com/Lightprotocol/light-protocol/pull/347/files#diff-ae098510c28e4ea810a9c0f3b0a070fccdd83301a3e2d7c424896ca2fb2474c2R167
Is this on purpose?

2023-10-19 17:08 UTC, vadorovsky commented on cli/src/psp-utils/constants.ts
>  export const PROGRAM_TAG = "v0.3.2";
No, sorry for missing it.

2023-10-19 19:14 UTC, vadorovsky commented
@ananas-block Comments addresses and I added a test. PTAL

2023-10-19 20:10 UTC, ananas-block approved these changes
Thanks for the changes!

2023-10-19 20:10 UTC, merged