feat: refactor sendSolanaTransactions
Lightprotocol/light-protocol pull request #425
Opened 2023-12-22 12:47 UTC by SwenSchaeferjohann

2024-01-05 22:30 UTC, ananas-block requested changes
Looks good in general!
Found one thing see comments.

2024-01-05 22:30 UTC, ananas-block commented on zk.js/src/relayer.ts
> +    prioritizationFee?: PrioritizationFee,
We should add the ``prioritizationFee`` to the relayer fee so that the relayer gets reimbursed for the cost.

2024-01-05 22:30 UTC, ananas-block commented on zk.js/src/relayer.ts
> +    prioritizationFee?: PrioritizationFee,
We could add the prioritization fee to the relayer as a property and add it when using getRelayerFee() and make the fee variable private to ensure that getRelayerFee() is being used everywhere.

2024-01-19 01:08 UTC, SwenSchaeferjohann commented
closing in favor of #448

2024-01-19 01:08 UTC, closed without merging