chore: prepare v1
Lightprotocol/light-protocol pull request #466
Opened 2024-02-12 21:35 UTC by ananas-block

2024-02-12 21:41 UTC, vadorovsky commented
Please update `Cargo.toml`, macro-circom is still being included there

2024-02-13 00:32 UTC, SwenSchaeferjohann requested changes
as michal said e.g lint/fmt are still looking for macro circom which fails the respective tests

2024-02-13 00:32 UTC, SwenSchaeferjohann commented on .github/workflows/light-sdk-tests.yml
> +#               "@lightprotocol/prover.js:test"
let's keep prover.js test

2024-02-13 00:32 UTC, SwenSchaeferjohann commented on .github/workflows/light-sdk-tests.yml
> +#               "@lightprotocol/circuit-lib.circom:test"]'
let's keep tests for circuitlib.js as well

2024-02-13 00:32 UTC, SwenSchaeferjohann commented on .github/workflows/light-system-programs-tests.yml
> +#       - "light-circuits/**"
did we have a light-circuits dir? 👀

2024-02-13 00:39 UTC, ananas-block commented on .github/workflows/light-system-programs-tests.yml
> +#       - "light-circuits/**"
that must have been a while ago

2024-02-13 11:12 UTC, SwenSchaeferjohann approved these changes
lgtm

2024-02-13 11:12 UTC, merged