refactor: add new programs and accounts to cli test-validator
Lightprotocol/light-protocol pull request #489
Opened 2024-02-28 00:53 UTC by ananas-block

2024-02-28 21:59 UTC, vadorovsky reviewed
I like generating accounts through a test! Left some minor comments.

2024-02-28 21:59 UTC, vadorovsky commented on cli/accounts/governance_authority_pda_3MtrKu5Mjgh3JqeE5PeRzw2Ld28XjFgbbph67E6UERSx.json
> +{"pubkey":"3MtrKu5Mjgh3JqeE5PeRzw2Ld28XjFgbbph67E6UERSx","account":{"lamports":1670400,"data":["92V2ansKL5F9ineLIqDCqQnhiwC5EFF0HDBN+u+Yy9c0sxQG63l/Mf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaa

2024-02-28 21:59 UTC, vadorovsky commented on programs/compressed-pda/tests/test.rs
> +async fn regnerate_accounts() {
```suggestion
async fn regenerate_accounts() {
```

2024-02-29 11:58 UTC, ananas-block commented on cli/accounts/governance_authority_pda_3MtrKu5Mjgh3JqeE5PeRzw2Ld28XjFgbbph67E6UERSx.json
> +{"pubkey":"3MtrKu5Mjgh3JqeE5PeRzw2Ld28XjFgbbph67E6UERSx","account":{"lamports":1670400,"data":["92V2ansKL5F9ineLIqDCqQnhiwC5EFF0HDBN+u+Yy9c0sxQG63l/Mf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA

2024-02-29 12:04 UTC, vadorovsky approved these changes
looks good, feel free to merge once green

2024-02-29 12:05 UTC, vadorovsky requested changes

2024-02-29 12:05 UTC, vadorovsky commented on scripts/getAccountState.sh
> +cd programs/compressed-pda && cargo test-sbf regnerate_accounts -- --ignored && cd -
You need to fix the typo here as well

```suggestion
cd programs/compressed-pda && cargo test-sbf regenerate_accounts -- --ignored && cd -
```

2024-02-29 19:05 UTC, ananas-block commented on scripts/getAccountState.sh
> +cd programs/compressed-pda && cargo test-sbf regnerate_accounts -- --ignored && cd -
fixed

2024-03-01 15:02 UTC, vadorovsky approved these changes

2024-03-01 15:03 UTC, merged